CREATE DATABASE ENJOY_GALAXY;
USE ENJOY_GALAXY;
CREATE TABLE USER (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(20) NOT NULL,
    FULLNAME VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(10) UNIQUE NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    WALLET DOUBLE CONSTRAINT CHECK_WALLET CHECK (WALLET >= 0),
    EDUCATION VARCHAR(50),
    JOBTITLE VARCHAR(50),
    SALARY DOUBLE CONSTRAINT CHECK_SALARY CHECK (SALARY >= 0),
    BIRTHDAY DATE,
    ADDRESS VARCHAR(300)
);
CREATE TABLE MOVIE (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) UNIQUE NOT NULL,
    DIRECTOR VARCHAR(100),
    ACTORS VARCHAR(500),
    GENRE VARCHAR(100),
    PREMIERE_DATE DATE,
    DURATION INT CONSTRAINT CHECK_DURATION CHECK (DURATION > 0),
    LANGUAGE VARCHAR(100),
    CONTENT VARCHAR(1000)
);
CREATE TABLE MOVIE_THEATER (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    NAME VARCHAR(100) UNIQUE NOT NULL,
    ADDRESS VARCHAR(200) UNIQUE NOT NULL
);
CREATE TABLE CINEMA (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    NUMBER_ROW_SEAT INT DEFAULT 4 CHECK (NUMBER_ROW_SEAT > 0),
    NUMBER_COLUMN_SEAT INT DEFAULT 4 CHECK (NUMBER_COLUMN_SEAT > 0),
    ID_MOVIE_THEATER BIGINT NOT NULL,
    FOREIGN KEY (ID_MOVIE_THEATER) REFERENCES MOVIE_THEATER(ID)
);
CREATE TABLE SHOWTIME (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME,
    ID_CINEMA BIGINT NOT NULL,
    FOREIGN KEY (ID_CINEMA) REFERENCES CINEMA(ID),
    ID_MOVIE BIGINT NOT NULL,
    FOREIGN KEY (ID_MOVIE) REFERENCES MOVIE(ID)
);
CREATE TABLE SEAT (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    CODE VARCHAR(3),
    READY BIT DEFAULT 1,
    ID_SHOWTIME BIGINT,
    FOREIGN KEY (ID_SHOWTIME) REFERENCES SHOWTIME(ID)
);
CREATE TABLE TICKET (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRICE DOUBLE NOT NULL CHECK (PRICE > 0),
    ID_USER BIGINT,
    FOREIGN KEY (ID_USER) REFERENCES USER(ID),
    ID_SEAT BIGINT,
    FOREIGN KEY (ID_SEAT) REFERENCES SEAT(ID),
    TIME_BOOKING DATETIME NOT NULL,
    PAID BIT DEFAULT 0,
    TIME_PAYMENT DATETIME,
    CHECKED BIT DEFAULT 0
);
INSERT INTO USER(TYPE, FULLNAME, PHONE_NUMBER, EMAIL, PASSWORD, WALLET) VALUES ("ADMIN", "Đoàn Hưởng", "0888442448",  "huong@gmail.com", "123", "1000000");
INSERT INTO MOVIE_THEATER(TYPE, NAME, ADDRESS) VALUES 
("STANDARD", "EG Hùng Vương", "126 Hồng Bàng, Phường 12, Quận 5"),
("STANDARD", "EG Hoàng Văn Thụ", "415, Hoàng Văn Thụ, Phường 2, Quận Tân Bình"),
("STANDARD", "EG Sư Vạn Hạnh", "11 Sư Vạn Hạnh, Phường 12, Quận 10"),
("STANDARD", "EG Đồng Khởi", "72 Lê Thánh Tôn & 45A Lý Tự Trọng, Quận 1"),
("STANDARD", "EG Thủ Đức", "216 Võ Văn Ngân, Phường Bình Thọ, Quận Thủ Đức");
ALTER TABLE `enjoy_galaxy`.`cinema` 
RENAME TO  `enjoy_galaxy`.`room` ;
ALTER TABLE `enjoy_galaxy`.`showtime` 
DROP FOREIGN KEY `showtime_ibfk_1`;
ALTER TABLE `enjoy_galaxy`.`showtime` 
CHANGE COLUMN `ID_CINEMA` `ID_ROOM` BIGINT NOT NULL ,
DROP INDEX `ID_CINEMA` ,
ADD INDEX `ID_ROOM` (`ID_ROOM` ASC) VISIBLE;
;
ALTER TABLE `enjoy_galaxy`.`showtime` 
ADD CONSTRAINT `showtime_ibfk_1`
  FOREIGN KEY (`ID_ROOM`)
  REFERENCES `enjoy_galaxy`.`room` (`ID`);
INSERT INTO ROOM(ID_MOVIE_THEATER, TYPE, NAME) VALUES
(2,"4DX","Hoàng Hôn"),
(2,"3D","Hoàng Tử"),
(2,"2D","Hoàng Hậu"),
(2,"IMAX","Hoàng Thượng"),
(1,"2D","Hùng Hổ"),
(1,"3D","Hùng Hục"),
(1,"4DX","Hùng Bá"),
(1,"IMAX","Hùng Hồn"),
(3,"3D","Sư Cọ"),
(3,"2D","Sư Cô"),
(3,"IMAX","Sư Thầy Ông Nội"),
(3,"4DX","Sư Phạm"),
(4,"IMAX","Đồng Chí"),
(4,"3D","Đồng Không Mông Lạnh"),
(4,"2D","Đồng Bào"),
(4,"4DX","Đồng Đô La"),
(5,"4DX","Thủ Lợn"),
(5,"2D","Thủ Dam"),
(5,"3D","Thủ Phủ"),
(5,"IMAX","Thủ Thành");
CREATE INDEX INDEX_ID_MOVIE_THEATER ON ROOM (ID_MOVIE_THEATER);
ALTER TABLE enjoy_galaxy.SEAT DROP CONSTRAINT `seat_ibfk_1`;
TRUNCATE TABLE SHOWTIME;
ALTER TABLE SEAT DROP CONSTRAINT `REFERENCES_SHOWTIME_ID`;
ALTER TABLE SEAT ADD CONSTRAINT `REFERENCES_SHOWTIME_ID` FOREIGN KEY (ID_SHOWTIME) REFERENCES SHOWTIME(ID);
CREATE INDEX INDEX_ID_ROOM ON SHOWTIME (ID_ROOM);
EXPLAIN SELECT * FROM SHOWTIME WHERE ID_ROOM = 5;
ALTER TABLE SHOWTIME DROP INDEX ID_ROOM;
ALTER TABLE SHOWTIME ADD COLUMN ROW_SEAT INT NOT NULL;
ALTER TABLE SHOWTIME ADD COLUMN COLUMN_SEAT INT NOT NULL;
ALTER TABLE SHOWTIME DROP COLUMN ROW_SEAT;
ALTER TABLE SHOWTIME DROP COLUMN COLUMN_SEAT;
SELECT * FROM SEAT;
EXPLAIN SELECT * FROM SEAT WHERE ID_SHOWTIME = 7;
CREATE INDEX INDEX_ID_SHOWTIME ON SEAT(ID_SHOWTIME);
ALTER TABLE movie_theater
RENAME TO  CINEMA;
ALTER TABLE `enjoy_galaxy`.`room` 
DROP FOREIGN KEY `room_ibfk_1`;
ALTER TABLE `enjoy_galaxy`.`room` 
CHANGE COLUMN `ID_MOVIE_THEATER` `ID_CINEMA` BIGINT NOT NULL ,
DROP INDEX `INDEX_ID_MOVIE_THEATER` ,
ADD INDEX `INDEX_ID_CINEMA` (`ID_CINEMA` ASC) VISIBLE;
;
ALTER TABLE `enjoy_galaxy`.`room` 
ADD CONSTRAINT `FK_CINEMA`
  FOREIGN KEY (`ID_CINEMA`)
  REFERENCES CINEMA (`ID`);
  ALTER TABLE `enjoy_galaxy`.`room` 
DROP FOREIGN KEY `room_ibfk_1`;
ALTER TABLE `enjoy_galaxy`.`room` 
ADD CONSTRAINT `FK_CINEMA`
  FOREIGN KEY (`ID_MOVIE_THEATER`)
  REFERENCES `enjoy_galaxy`.`movie_theater` (`ID`);
  ALTER TABLE `enjoy_galaxy`.`seat` 
ADD COLUMN `CAPACITY` INT NOT NULL DEFAULT 1 AFTER `ID_SHOWTIME`;
ALTER TABLE SEAT CHANGE COLUMN `ISEMPTY` `IS_EMPTY` BIT(1) NULL DEFAULT b'1' ;
ALTER TABLE MOVIE ADD COLUMN IMAGE VARCHAR(500) UNIQUE;
UPDATE MOVIE SET IMAGE = "https://firebasestorage.googleapis.com/v0/b/module-3-daf70.appspot.com/o/1.jpg?alt=media&token=fbbed138-34ca-49d2-87f1-42581be57609"
WHERE ID = 1;
UPDATE MOVIE SET IMAGE = "https://firebasestorage.googleapis.com/v0/b/module-3-daf70.appspot.com/o/2.jpg?alt=media&token=c02fa731-b3f0-4128-a1f6-a3f537c95508"
WHERE ID = 2;
UPDATE MOVIE SET IMAGE = "https://firebasestorage.googleapis.com/v0/b/module-3-daf70.appspot.com/o/3.jpg?alt=media&token=0f0dc405-b240-4f94-b4ca-8647010c9839"
WHERE ID = 3;
ALTER TABLE `enjoy_galaxy`.`movie` 
CHANGE COLUMN `IMAGE` `URL_IMAGE` VARCHAR(500) UNIQUE ;